steps:
  # 1) Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/hello-k8s-app:$COMMIT_SHA'
      - '.'
    
  # 2) Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/hello-k8s-app:$COMMIT_SHA'

  # 3) Deploy to GKE: Update the existing Deployment's container image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy to GKE'
    # Set environment variables so 'kubectl' knows which cluster & zone to use
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'        # <-- Adjust to match your cluster's zone
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-gke-cluster'  # <-- Your GKE cluster name
    args:
      - 'set'
      - 'image'
      - 'deployment/hello-deployment'  # Must match the name of your Deployment in deployment.yaml
      - 'hello-container=gcr.io/$PROJECT_ID/hello-k8s-app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/hello-k8s-app:$COMMIT_SHA'

